### ISSUE TITLE
通知先をidobataにする

### ISSUE THREAD

**Issue by shunji-yamaguchi** [esm-bits/novice-timer#11]

**Comment by fossamagna** [comment]
> 通知を送るidobataのURLはディフォルトで設定されており、PUTリクエストで更新できる。

まずは設定ファイル(`application.yml`)に設定されているURLを利用するくらいでもいいかも。

**Comment by shunji-yamaguchi** [comment]
**機能**
通知内容を受け取り、idobataのフックへPOSTリクエストを送る。
通知を送るidobataのURLは、設定ファイル(`application.yml`)に設定する。

以上のように修正いたしました。レビューをよろしくお願い致します。

**Comment by sakai-y** [comment]
👍

**Comment by t-kunou** [comment]
``application.yml`` はリポジトリ管理するつもりですか？
idobataのhookのURLは公開リポジトリに置かないほうが良いと思います。

**Comment by sakai-y** [comment]
リポジトリの`application.yml`にはダミーのURLを書いておいて、実行環境側に置く`application.yml`の内容で上書き、ですかね。

**Comment by t-kunou** [comment]
なるほど。
その辺をうまくやるのでしたら良いと思います ⭐️

**Comment by shunji-yamaguchi** [comment]
**機能**
通知内容を受け取り、idobataのフックへPOSTリクエストを送る。
通知を送るidobataのURLは、設定ファイル(application.yml)に設定する。
`application.yml`はダミー用と実行環境用を作成し、ダミー用のみリポジトリ管理する。

以上のように修正いたしました。レビューをよろしくお願い致します。

**Comment by fossamagna** [comment]
`application.yml`には何も書かずに実行時に環境変数やアプリケーションの引数で指定するのがいいなじゃないでしょうか？
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by sakai-y** [comment]
何も書かないと、プロパティ名が分からなくなったりしないかな〜、とか。

**Comment by fossamagna** [comment]
> 何も書かないと、プロパティ名が分からなくなったりしないかな〜、とか。

では、空文字列にしておくというではどうでしょう。

**Comment by shunji-yamaguchi** [comment]
`application.yml`はダミー用とし、別に実行環境用を作成する。
ダミー用のみリポジトリ管理し、URLは空文字列とする。
実装する際は環境変数を指定して、実行環境用の設定ファイルに切り替える。

以上のように考えました。あってますでしょうか？

**Comment by fossamagna** [comment]
> ダミー用のみリポジトリ管理し、URLは空文字列とする。

本番用でも秘密にしたい情報以外はリポジトリで管理してもいいんじゃないでしょうか？今はない(秘密にしておきたいものしかない)のかもしれませんが。

> 実装する際は環境変数を指定して、実行環境用の設定ファイルに切り替える。

環境変数は実行時に指定するものですね。
また、ファイル(設定値)の切り替えには https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-profile-specific-properties が利用できます。

**Comment by shunji-yamaguchi** [comment]
**機能**
通知内容を受け取り、idobataのフックへPOSTリクエストを送る。
通知を送るidobataのURLは、設定ファイル(`application.yml`)に設定する。
`application.yml`はダミー用とし、URLを表すプロパティは空文字列とする。
実行環境用として、実際のURLを記述した設定ファイルを作成し、このファイルはリポジトリ管理から外す。
実行する際は環境変数を指定して、実行環境用の設定ファイルに切り替える。

以上のように修正いたしました。レビューをよろしくお願い致します。

**Comment by sakai-y** [comment]
単に環境変数で上書きするか、実行時にjarと同じ場所に置いた`application.yml`で上書きするか、どっちかなのかと思ってました。

**Comment by shunji-yamaguchi** [comment]
申し訳ありません。eclipseで実行する場合しか想定できていないのですが、

ダミー用の`application.yml`と本番用の`application-production.yml`があり、実行時に`SPRING_PROFILES_ACTIVE = production`を指定して実行するのを考えています。

**Comment by sakai-y** [comment]
やってみた？

**Comment by shunji-yamaguchi** [comment]
はい

`src/main/resources/config`パッケージに`application.yml`と`application-production.yml`を作成し、
記述したプロパティの値を読み込めました。
eclipseの`実行の構成`の`環境`に変数`SPRING_PROFILES_ACTIVE`を追加して、`application-production.yml`の値に切り替えができました。

**Comment by sakai-y** [comment]
でも、ビルド時に`application-production.yml`（というか本当のURLの設定）はないんですよね？
アプリケーションが複数のプロファイルを「持って」いて、それを切り替えるのか、ある設定値を実行時に上書きするのか、想定している使い方としてはどちらでしょう。

**Comment by shunji-yamaguchi** [comment]
アプリケーションが複数のプロファイルを持っていて、それを切り替えるのを想定しております。

複数のプロファイルは、urlプロパティが空文字列の`application.yml`とurlプロパティが実際のidobataのフックurlである`application-production.yml`の2つを想定しています。

**Comment by sakai-y** [comment]
> urlプロパティが実際のidobataのフックurlであるapplication-production.yml

これは、どの時点でどこに存在する想定？

**Comment by shunji-yamaguchi** [comment]
実装しているときも、eclipseでローカルホストで実行するときも、本番環境にデプロイするときも、`application.yml`と同じ場所(パッケージ)にある想定です。

**Comment by sakai-y** [comment]
なるほど。ビルド時に普通に存在するけど、単にGit管理外にする想定ってことかな。

**Comment by shunji-yamaguchi** [comment]
はい、そうです。
申し訳ありません。書き方が不適切でした。

> 実行環境用として、実際のURLを記述した設定ファイルを作成し、このファイルはリポジトリ管理から外す。

これは`実行環境用として、実際のURLを記述した設定ファイルを作成し、このファイルはGitの管理から外す。`という意味のつもりでした。

**Comment by sakai-y** [comment]
なるほど。じゃあ、今後、本番環境用の設定だけどGitで管理したいもの、ができたらどうしよう。

**Comment by shunji-yamaguchi** [comment]
> 本番環境用の設定だけどGitで管理したいもの、ができたら

困りますね。。。
本番環境用の設定だけどGitで管理したい設定用のプロファイルを作ればよいのでしょうか？

---

インタフェースについて以下のように考えました。レビューをよろしくお願い致します。

**リクエスト**
パス：POST api/notices
リクエストボディ：
```json
{ "message": "通知内容" }
```

**レスポンス**
HTTPステータスコード：204 No Content
リクエストボディ：なし

**Comment by sakai-y** [comment]
このAPIは、いつ使う想定？
タイマー開始前？後？

タイマー開始のリクエストが時間＋通知内容になってばいいんじゃないかと思うんだけど、別にした意図は？

**Comment by sakai-y** [comment]
> 本番環境用の設定だけどGitで管理したい設定用のプロファイルを作ればよいのでしょうか？

ビルド時の構成：
  `application.yml` - デフォルト設定
  `application-{profile}.yml` - プロファイル毎の設定

で、これらのファイルはGitで管理する。
もちろん秘匿情報は書かない。

で、実行時に、
  アプリ.jar
  `application.yml` - 上書きする設定
と配置して、この`application.yml`には正しい設定を書く。

って感じかな。

**Comment by shunji-yamaguchi** [comment]
> 別にした意図は？

通知する内容もリソースだと考え、またアジェンダの内容を通知する際にはタイマー以外からも呼び出されるとも考えて、別にしました。
APIとして用意せずに、通知機能を持ったインスタンスをDIコンテナに生成して、通知する際に呼び出せば良いでしょうか？

> って感じかな。

秘匿情報のプロファイルはjarとは別に用意すると良いのですね、ありがとうございます。

**Comment by sakai-y** [comment]
いまいち想定が分からないなぁ。
現状、標準出力に表示しているものを、idobataにする、というのが、このIssueで対応して欲しいことです。

**Comment by shunji-yamaguchi** [comment]
かしこまりました。一度コードを書いてPUSHしてみます。
