### ISSUE TITLE
実行中のタイマーを途中で停止するAPIを作る

### ISSUE THREAD

**Issue by hironoriohashi** [esm-bits/novice-timer#12]

**Comment by hironoriohashi** [comment]
GETのリクエストを受けて、動作中のタイマーを止める処理を行う。

以上のように考えました。
具体的なインターフェースは今考えています。

**Comment by sakai-y** [comment]
GETに副作用があるのはよくないねぇ

**Comment by hironoriohashi** [comment]
> GETに副作用があるのはよくないねぇ

HEADだと適切ですか？

**Comment by sakai-y** [comment]
RESTでHEAD使わないw

**Comment by hironoriohashi** [comment]
この場合、DELETEのリクエストを受けて動作中のタイマーを止める処理を行うのが正しいですか？

**Comment by sakai-y** [comment]
どう考えるかやけどねぇ。
動作中タイマーの状態を更新する、ってことで、PUTでいいと思います。

**Comment by hironoriohashi** [comment]
> 動作中タイマーの状態を更新する、ってことで、PUTでいいと思います。

分かりました。では、具体的なところを考えます。

**Comment by hironoriohashi** [comment]
実行中のタイマーを途中で停止するAPIのリクエストとレスポンスを以下のように考えました。
レビューお願いします。

リクエスト :
パス : PUT api/timers

 ---

レスポンス :
httpステータス : 202 Accepted

**Comment by sakai-y** [comment]
パラメータなし？

**Comment by hironoriohashi** [comment]
タイマーは２つ以上使わないと思い、パラメータは無しにしました。

**Comment by sakai-y** [comment]
PUTは何かを更新したいリクエストなんだけど、パラメータがないと何をどう更新するか分からない。
・・・まあ今はタイマーは１つで停止しかできないのであれば、パラメータなしでも・・・。
それならDELETEの方がマシかも。

**Comment by sakai-y** [comment]
一旦DELETEで進めよう。

**Comment by hironoriohashi** [comment]
今後、PUTのリクエストが増えると考えると、
リクエスト：
パス：PUT api/timers
リクエストボディ：
```json
{
    "id": 1,
    "request": "stop"
}
```
とした方が良いですか？

**Comment by hironoriohashi** [comment]
> 一旦DELETEで進めよう。
分かりました。

**Comment by hironoriohashi** [comment]
実行中のタイマーを途中で停止するAPIのリクエストとレスポンスを以下のように変えました。
レビューお願いします。

リクエスト :
パス : DELETE api/timers

---
レスポンス :
httpステータス : 202 Accepted

**Comment by sakai-y** [comment]
レスポンス時に停止しているなら200でよいです。

**Comment by hironoriohashi** [comment]
> レスポンス時に停止しているなら200でよいです。

分かりました。以下のように変更しました。
リクエスト :
パス : DELETE api/timers

---
レスポンス :
httpステータス : 200 OK

**Comment by t-kunou** [comment]
（この停止は一時停止ではなくて中止なんですね）

**Comment by fossamagna** [comment]
> リクエスト :
> パス : DELETE api/timers

止めるタイマーの`id`はどうやって指定するんだろう。。。。

**Comment by sakai-y** [comment]
今はタイマー１個しか動かないからDELETEでいいかなと。
アジェンダ対応したら発表番号的なものが必要になると思います。

**Comment by hironoriohashi** [comment]
> アジェンダ対応したら発表番号的なものが必要になると思います。

ここでidに当たるものを用意した方がいいですか？

**Comment by fossamagna** [comment]
必要になったらでいいですよ。

**Comment by hironoriohashi** [comment]
> 必要になったらでいいですよ。

分かりました。
