### ISSUE TITLE
タイマー開始時に時間と一緒に発表者アカウントを受け取って、通知時にメンションする

### ISSUE THREAD

**Issue by shunji-yamaguchi** [esm-bits/novice-timer#15]

**Comment by shunji-yamaguchi** [comment]
**機能**
タイマー開始時に時間と一緒に発表者のidobataアカウントをPOSTで送る
通知の際に受け取ったアカウントへメンションする
 
---
**インタフェース**
リクエスト：
パス: POST api/timers
リクエストボディ:
``` json
{
    "seconds": 30,
    "mention": "メンション"
}
```

レスポンス：
httpステータス: 201 Created

以上のように考えました。レビューをよろしくお願い致します。

**Comment by sakai-y** [comment]
`idobata_user`がいいな

**Comment by hironoriohashi** [comment]
以下のように変更しました。レビューよろしくお願い致します。
#2 の"idobata_name"も"idobata_user"に統一した方が良いですか？

**機能**
タイマー開始時に時間と一緒に発表者のidobataアカウントをPOSTで送る
通知の際に受け取ったアカウントへメンションする
 
---
**インタフェース**
リクエスト：
パス: POST api/timers
リクエストボディ:
``` json
{
    "seconds": 30,
    "idobata_user": "idobataアカウント"
}
```

レスポンス：
httpステータス: 201 Created

**Comment by sakai-y** [comment]
#2 は一旦おいといて、これで進めましょう。

**Comment by hironoriohashi** [comment]
ソースコードで、"idobata_user"を格納するフィールドをキャメルケースに修正するので、以下のように変更しようと思います。

---
**インタフェース**
リクエスト：
パス: POST api/timers
リクエストボディ:
``` json
{
    "seconds": 30,
    "idobataUser": "idobataアカウント"
}
```

レスポンス：
httpステータス: 201 Created

**Comment by sakai-y** [comment]
JSONのIFは変更せず、Javaのフィールド名だけ変更して、動かしてみてください。

**Comment by hironoriohashi** [comment]
> JSONのIFは変更せず、Javaのフィールド名だけ変更して、動かしてみてください。

動きました。
インタフェースは変更せずに進めます。
