### ISSUE TITLE
複数のタイマー情報をあらかじめ受け取って保持する

### ISSUE THREAD

**Issue by shunji-yamaguchi** [esm-bits/novice-timer#16]

**Comment by shunji-yamaguchi** [comment]
以下のように考えました。よろしくお願い致します。
質問なのですが、タイマーの情報はデータベースに保存するのが良いのでしょうか？

**機能**
複数のタイマーの情報をPOSTで送信し、保持する
 
**インタフェース**
リクエスト：
パス: POST api/timers
リクエストボディ: 
````json
{
    "timers": [
        { "seconds": 10, "idobata_user": "shunji-yamaguchi" },
        { "seconds": 10, "idobata_user": "hironoriohashi" }
    ]
}
````
 
レスポンス：
HTTPステータス: 201 Created
レスポンスボディ:
````json
{
    "timers": [
        { "id": 1, "seconds": 10, "idobata_user": "shunji-yamaguchi" },
        { "id": 2, "seconds": 10, "idobata_user": "hironoriohashi" }
    ]
}
````

**Comment by shunji-yamaguchi** [comment]
`複数のタイマー情報をあらかじめ受け取って保持しておくIF`についてですが、複数のタイマーを一度にまとめて保存できる機能と受け取っていたのですか、あってますでしょうか？

**Comment by sakai-y** [comment]
１つ１つにID振っちゃう？全体で１つでよさそうな気も。

**Comment by sakai-y** [comment]
> 質問なのですが、タイマーの情報はデータベースに保存するのが良いのでしょうか？

DBの設計しないといけなくなるので、一旦メモリでよいですが、Repositoryクラスは用意して、そこで保持するようにしてください。
Repositoryだけスタブの状態。

**Comment by shunji-yamaguchi** [comment]
> Repositoryクラスは用意して、そこで保持する

かしこまりました。ありがとうございます。

----

以下のように修正いたしました。よろしくお願い致します。

**インタフェース**
リクエスト：
パス: POST api/timers
リクエストボディ: 
````json
{
    "timeLimits": [
        { "seconds": 10, "idobata_user": "user1" },
        { "seconds": 10, "idobata_user": "user2" }
    ]
}
````
 
レスポンス：
HTTPステータス: 201 Created
レスポンスボディ:
````json
{
    "id": 1,
    "timeLimits": [
        { "id": 1, "seconds": 10, "idobata_user": "user1" },
        { "id": 2, "seconds": 10, "idobata_user": "user2" }
    ]
}
````

**Comment by sakai-y** [comment]
👌

**Comment by shunji-yamaguchi** [comment]
リクエストのパスを`api/multipleTimers`に変更しようと考えたのですが、適切でしょうか？
適切な場合、パスのルートが`api/timers`である`TimerRestControllerクラス`とは別のコントローラクラスを作成すればよいでしょうか？

**Comment by sakai-y** [comment]
実装クラスは変更しなくていいです。

**Comment by sakai-y** [comment]
ダメか。このissueで、発表のタイトルも受け付けるようにして、アジェンダ登録ってことにしちゃいますか

**Comment by shunji-yamaguchi** [comment]
**機能**
アジェンダの情報をPOSTで送信し、保持する

**インタフェース**
リクエスト：
パス: POST api/agends
リクエストボディ:
[
    { "seconds": 10, "idobata_user": "user1" },
    { "seconds": 10, "idobata_user": "user2" }
]
レスポンス：
HTTPステータス: 201 Created
レスポンスボディ:

[
    { "id": 1, "seconds": 10, "idobata_user": "user1" },
    { "id": 2, "seconds": 10, "idobata_user": "user2" }
]

**Comment by shunji-yamaguchi** [comment]
#2 のインタフェースをそのまま使用すれば良いでしょうか？
それとも以下のように最低限の情報だけ扱えばよいでしょうか？

レスポンスボディ：
````json
{
    "id": 1,
    "presen": [
        {
            "title": "プレゼンタイトル",
            "idobata_user": "idobataのアカウント名",
            "minutes": 5
        },
    ],
}
````
リクエストボディではidなし

**Comment by sakai-y** [comment]
プレゼン・・・

**Comment by shunji-yamaguchi** [comment]
横着しておりました。申し訳ありません。
以下のように修正いたしました。よろしくお願い致します。

**機能**
アジェンダの内容をPOSTで送信して、保持する

**インタフェース**
リクエスト：
パス: api/agendas
リクエストボディ: 
````json
{
    "agenda": [
        {
            "title": "発表タイトル",
            "idobata_user": "idobataのアカウント名",
            "minutes": 5
        }
    ]
}
````

レスポンス：
HTTPステータス: 201 Created
レスポンスボディ: 
````json
{
    "id": 1,
    "agenda": [
        {
            "title": "発表タイトル",
            "idobata_user": "idobataのアカウント名",
            "minutes": 5
        }
    ]
}
````

**Comment by shunji-yamaguchi** [comment]
json内の配列名を`subjects`に変更いたしました。よろしくお願い致します。

**機能**
アジェンダの内容をPOSTで送信して、保持する

**インタフェース**
リクエスト：
パス: POST api/agendas
リクエストボディ: 
````json
{
    "subjects": [
        {
            "title": "発表タイトル",
            "idobata_user": "idobataのアカウント名",
            "minutes": 5
        }
    ]
}
````

レスポンス：
HTTPステータス: 201 Created
レスポンスボディ: 
````json
{
    "id": 1,
    "subjects": [
        {
            "title": "発表タイトル",
            "idobata_user": "idobataのアカウント名",
            "minutes": 5
        }
    ]
}
````

**Comment by sakai-y** [comment]
`agenda`より`subjects`がいいと思ったのはナゼ？
（単なる質問です）

**Comment by shunji-yamaguchi** [comment]
json全体が一つのアジェンダで、配列は発表の集まりだと考えました。

**Comment by sakai-y** [comment]
LGTM

**Comment by shunji-yamaguchi** [comment]
````json
{
    "subjects": [
        {
            "title": "発表タイトル",
            "idobata_user": "idobataのアカウント名",
            "minutes": 5
        }
    ]
}
````
の実装についてなのですが、`subjects`の要素であるオブジェクトの`idobata_user`と`minutes`は今の`TimeLimitクラス`が定義しています。
そこでjsonの形式を
````json
{
    "subjects": [
        {
            "title": "発表タイトル",
            "timeLimit": {
                "idobata_user": "idobataのアカウント名",
                "minutes": 5
            }
        }
    ]
}
````
に変更しようと考えたのですが、適切でしょうか？

**Comment by sakai-y** [comment]
不適切ですね。現状は、元々`秒`の指定だけができるところから始まって、だから`TimeLimit`だったわけで、今回、情報の単位が大きくなった（それによって意味が変わった）ので、`TimeLimit`を変更すべき時が来たわけです。

**Comment by shunji-yamaguchi** [comment]
では今の`TimeLimitクラス`を`Subjectクラス`に変更すればよいでしょうか？

**Comment by sakai-y** [comment]
ですね。
