### ISSUE TITLE
アジェンダを入力できる機能を作成する

### ISSUE THREAD

**Issue by hironoriohashi** [esm-bits/novice-timer#2]

**Comment by hironoriohashi** [comment]
- 以下の内容を入力できるフォームを作成
1.アジェンダのタイトル
2.開始時刻と終了時刻
3.発表の順番、プレゼンのタイトル、発表者、発表時間(増減可能)
4.備考のテキストボックス
5.作成(Submit)ボタン

以上のように考えました。
レビューお願いします。

**Comment by sakai-y** [comment]
一旦ページは忘れよう。サーバー側の機能だけ考えて。

**Comment by sakai-y** [comment]
`発表の順番`と明記してるのは、見た目の順番と別に`発表順`が設定できることを想定しているの？

**Comment by sakai-y** [comment]
`発表者`は名前？だけ？

**Comment by hironoriohashi** [comment]
> 発表の順番と明記してるのは、見た目の順番と別に発表順が設定できることを想定しているの？

はい、そうです。デフォルトでは昇順で番号が振ってあります。

> 発表者は名前？だけ？

発表者名のつもりです。

**Comment by sakai-y** [comment]
> はい、そうです。デフォルトでは昇順で番号が振ってあります。

番号で管理しようとすると重複したらどうするの？とか問題を複雑にする可能性があります。
順番を変更したいのであれば、見た目もろとも変更したらいいんでは。
＃まあ、ページのことは一旦考えないw

**Comment by sakai-y** [comment]
> 発表者名のつもりです。

経過時間etcの通知、発表者にメンションはしない？

**Comment by hironoriohashi** [comment]
> 経過時間etcの通知、発表者にメンションはしない？

確かに、idobataのアカウントもあった方が良いですね。

**Comment by hironoriohashi** [comment]
アジェンダの内容を入力
　アジェンダのタイトル
　開始時刻と終了時刻
　プレゼンのタイトル、発表者名、idobataアカウント、発表時間
   備考
これらをPOSTして、データベースに保存する

以上のように変更しました。
レビューお願いします。

**Comment by sakai-y** [comment]
いいと思います。
具体的なインターフェース（パス、POSTデータの形式、レスポンス内容など）を決めましょう。

**Comment by hironoriohashi** [comment]
新規アジェンダ入力画面パス：GET v1/timers/new
POSTデータの形式：
{
　”agenda”:”アジェンダのタイトル”,
　“start”:1707071830,　(開始時間、この場合2017年7月7日18時30分となる)
　“end”:1707071930,　(終了時間)
　”presen”:[
　　　{
　　　　”title”:”プレゼンタイトル”,
　　　　”name”:”発表者名”,
　　　　”idobata_name”:”idobataのアカウント名”,
　　　　”time”:5　(発表時間、この場合5分)
　　　},
　　　.........................
　　],
　　 “remarks”:”備考”
}
POST送信先パス：POST v1/agendas
レスポンス：GET v1/agendas/1/(作成時に自動で振られるidが1だった場合)

以上のように考えました。
レビューお願いします。

**Comment by hironoriohashi** [comment]
レスポンス：
　HTTPステータス：201 Created
　レスポンスボディ：
　{
　　”id”:1 ,(作成時につけられるid)
　　以下送信時と同様
　}

レスポンスを以上のように変更しました。
レビューお願いします。

**Comment by hironoriohashi** [comment]
新規アジェンダを登録するリクエストとレスポンスを修正しました。
レビューお願いします。

新規アジェンダの登録
リクエスト：
　パス：POST agendas/
　リクエストボディ：
　{
　　”agenda”: ”アジェンダのタイトル”,
　　“start”: 1707071830,
　　“end”: 1707071930,
　　”presen”: [
　　　　{
　　　　　”title”: ”プレゼンタイトル”,
　　　　　”name”: ”発表者名”,
　　　　　”idobata_name”: ”idobataのアカウント名”,
　　　　　”time_minutes”: 5
　　　　},
　　　　.........................
　　],
　　“remarks”: ”備考”
　}
 
“start”: 1707071830, (開始時間、この場合2017年7月7日18時30分となる)
“end”: 1707071930, (終了時間)
“time_minutes”: 5, (発表時間、この場合5分)

 ----
レスポンス：
　HTTPステータス：201 Created
　レスポンスボディ：
　　{
　　　”id”: 1,
　　　以下送信時と同様
　　}
 
”id”: 1, (作成時につけられるid)

**Comment by sakai-y** [comment]
日付・時刻についてはISO8601フォーマットにしましょう。[参考](http://qiita.com/kidatti/items/272eb962b5e6025fc51e)

あと、JSONならMarkdownで
<pre>```json
〜
```</pre>
と記述しましょう。

**Comment by hironoriohashi** [comment]
新規アジェンダを登録するリクエストとレスポンスを修正しました。
レビューお願いします。

新規アジェンダの登録
リクエスト：
　パス：POST agendas/
　リクエストボディ：
``` json
{
    "agenda": "アジェンダのタイトル",
    "start": "20170707T183000+0900",
    "end": "20170707T193000+0900",
    "presen": [
        {
            "title": "プレゼンタイトル",
            "name": "発表者名",
            "idobata_name": "idobataのアカウント名",
            "time_minutes": 5
        },
    ],
    "remarks": "備考"
}
```
"start": "20170707T183000+0900", (開始時間、この場合2017年7月7日18時30分となる)
"end": "20170707T193000+0900", (終了時間)
“time_minutes”: 5, (発表時間、この場合5分)
 
---
レスポンス：
 
　HTTPステータス：201 Created
　レスポンスボディ：
``` json
{
    "id": 1,
    "agenda": "アジェンダのタイトル",
    "start": "20170707T183000+0900",
    "end": "20170707T193000+0900",
    "presen": [
        {
            "title": "プレゼンタイトル",
            "name": "発表者名",
            "idobata_name": "idobataのアカウント名",
            "time_minutes": 5
        },
    ],
    "remarks": "備考"
}
```
”id”: 1, (作成時につけられるid)

**Comment by shunji-yamaguchi** [comment]
#16 で対応
