### ISSUE TITLE
N番目のSubjectを開始・停止するIFを作成する

### ISSUE THREAD

**Issue by hironoriohashi** [esm-bits/novice-timer#23]

**Comment by hironoriohashi** [comment]
agendaの`id`をURLに入れ、
subjectの番号と開始or停止の選択をjsonで渡してタイマーを開始or停止する

上記のように考えました。
レビューお願いします。

**Comment by sakai-y** [comment]
もうちょっと具体的なやつを・・・

**Comment by hironoriohashi** [comment]
インタフェース
リクエスト：
パス: PUT api/agendas/1/subject/
リクエストボディ:
{
    “No”: 1
    “operation”: “Start”
}
 
レスポンス：
httpステータス: 200 or 404

**Comment by sakai-y** [comment]
連番はパスに含めてしまってもよさそうな気もするけど、単なる好みなのかな〜。
誰か〜。

**Comment by t-kunou** [comment]
> 連番はパスに含めてしまってもよさそうな気もするけど、単なる好みなのかな〜。

``api/agendas/1/subject/1`` みたいな感じですかね。そっちの方がCRUD感はありますね。

**Comment by hironoriohashi** [comment]
下記のように修正しました。レビューお願いします。

インタフェース
リクエスト：
パス: PUT api/agendas/1/subject/1
リクエストボディ:
{
“operation”: “Start”
}

レスポンス：
httpステータス: 200 or 404

**Comment by sakai-y** [comment]
**操作**はメソッド（この場合はPUT）なんですよね〜。
状態を更新する、と考えるのがいいんじゃなかろうか。
あと、なんとなく大文字キモい

**Comment by hironoriohashi** [comment]
分かりました。修正します。

**Comment by hironoriohashi** [comment]
`operation`を`update`に変更しようと思いますが、適切でしょうか？

**Comment by sakai-y** [comment]
なんで`update`？

**Comment by hironoriohashi** [comment]
`更新`を翻訳したら`update`と出たので...

**Comment by sakai-y** [comment]
説明が足りなかったですね。
「**操作**はメソッド」、この場合は、`PUT`が「更新」操作になります。

**Comment by hironoriohashi** [comment]
では、`state`にすると適切ですか？

**Comment by sakai-y** [comment]
💯

**Comment by hironoriohashi** [comment]
下記のように修正しました。レビューお願いします。

インタフェース
リクエスト：
パス: PUT api/agendas/1/subject/1
リクエストボディ:
```json
{
"state": "start"
}
```
レスポンス：
httpステータス: 200 or 404

**Comment by hironoriohashi** [comment]
停止のインタフェースを追加しました。レビューお願いします。

下記のように修正しました。レビューお願いします。

インタフェース
- 開始の場合
リクエスト：
パス: PUT api/agendas/1/subject/1
リクエストボディ:
```json
{
"state": "start"
}
```
レスポンス：
httpステータス: 200 or 404

- 停止の場合
リクエスト：
パス: PUT api/agendas/1/subject/1
リクエストボディ:
```json
{
"state": "stop"
}
```
レスポンス：
httpステータス: 200 or 404

**Comment by sakai-y** [comment]
問題ないと思うけど、書き方が冗長。
違いは`state`の値だけなので、もっとコンパクトに書けるはず。

あと・・・JSON内にインデントなくて気持ち悪いと思っているのはオレだけではないはず。

**Comment by hironoriohashi** [comment]
分かりました。修正します。

**Comment by hironoriohashi** [comment]
下記のように修正しました。レビューお願いします。

インタフェース


リクエスト：
パス: PUT api/agendas/1/subject/1

リクエストボディ:
- 開始の場合
```json
{
    "state": "start"
}
```
- 停止の場合
```json
{
    "state": "stop"
}
```
レスポンス：
httpステータス: 200 or 404

**Comment by sakai-y** [comment]
👌

**Comment by shunji-yamaguchi** [comment]
#29 の`N番目のsubject内容を更新する機能`とパスが被るため

リクエスト：
パス: PUT api/agendas/{id}/subjects/{number}/timers

に変更
