### ISSUE TITLE
通知内容を日本語に対応させる

### ISSUE THREAD

**Issue by hironoriohashi** [esm-bits/novice-timer#26]

**Comment by hironoriohashi** [comment]
- 方法1 Unicodeのコードポイントを入力する(コードポイントに変換する)
`$ curl http://localhost:8080/api/agendas/ -i -XPOST -H "Content-Type: application/json" -d "{\"subjects\": [{\"title\": \"\\u30C6\\u30B9\\u30C8\",\"minutes\": 3,\"idobata_user\": \"hironoriohashi\"}]}"`

- 方法2 .json形式のファイルを渡す
`$ curl http://localhost:8080/api/agendas/ -i -XPOST -H "Content-Type: application/json" -d @jsonfile.json`

**Comment by t-kunou** [comment]
```bash
$ curl http://localhost:8080/api/agendas/ -i -XPOST -H "Content-Type: application/json" -d "{\"subjects\": [{\"title\": \"\\u30C6\\u30B9\\u30C8\",\"minutes\": 3,\"idobata_user\": \"hironoriohashi\"}]}"
```

自分でコードポイント書くんですか…
Windowsさんには困ったもんですね…

nkf使えるなら、こんなのはどうですかね？ ※ 手元にWindows環境がないので動くか分かりません。
```bash
$ curl http://localhost:8080/api/agendas/ -i -XPOST -H "Content-Type: application/json" -d "{\"subjects\": [{\"title\": \"`echo ほげ | nkf -w`\",\"minutes\": 3,\"idobata_user\": \"hironoriohashi\"}]}"
```

**Comment by hironoriohashi** [comment]
> nkf使えるなら、こんなのはどうですかね？

ありがとうございます。試してみます。

**Comment by hironoriohashi** [comment]
`Restlet Client - REST API Testing`を使ってリクエストボディを送った場合、
全角文字の入力ができたので以降これを使おうと思います。

**Comment by hironoriohashi** [comment]
通知内容を全角文字で送る方法を追記します。
- 方法3
`Restlet Client - REST API Testing`を使い、`REQUESTS`に送るリクエストを入力し、`send`ボタンより送信する

**Comment by sakai-y** [comment]
LGTM
