### ISSUE TITLE
登録済みのアジェンダを取得する機能を作成する

### ISSUE THREAD

**Issue by shunji-yamaguchi** [esm-bits/novice-timer#27]

**Comment by shunji-yamaguchi** [comment]
**機能**
1.GETリクエストを受け、アジェンダの内容を返す。
2.URLにidが付与されている場合は、idの対応するアジェンダの内容を返す。

**1.インタフェース**
リクエスト：
パス：GET api/agendas
リクエストボディ：なし

レスポンス：
HTTPステータス：200 OK
レスポンスボディ：
```json
[
    {
        "id": 1,
        "subjects": [
            {
                "title": "発表タイトル",
                "idobata_user": "idobataのアカウント名",
                "minutes": 5
            }
        ]
    }
] 
```

**2.インタフェース**
リクエスト：
パス：GET api/agendas/1
リクエストボディ：なし

レスポンス：
HTTPステータス：200 OK || 404 Not Found
レスポンスボディ：
```json
{
    "id": 1,
    "subjects": [
        {
            "title": "発表タイトル",
            "idobata_user": "idobataのアカウント名",
            "minutes": 5
        }
    ]
}
````

----

以上のように考えました。よろしくお願い致します。

**Comment by shunji-yamaguchi** [comment]
このインタフェースで実装を進めてもよいでしょうか？

**Comment by shunji-yamaguchi** [comment]
**2.インタフェース**において`GET api/agendas/1`にアクセスした際にagendaがない場合、`404 Not Found`を返すとしておりました。

しかし #24 の実装では、agendaがない場合はIllegalArgumentExceptionをスローし、`400 Bad Request`を返しています。

そこでこれに合わせてagendaがない場合は`400 Bad Request`を返すよう変更しようと思うのですが、適切でしょうか？

**Comment by sakai-y** [comment]
取得IFでは、存在しない場合は404を返したいですね。

**Comment by shunji-yamaguchi** [comment]
かしこまりました。404のままで実装いたします。
