### ISSUE TITLE
登録済みのアジェンダの内容を更新する機能を追加する

### ISSUE THREAD

**Issue by hironoriohashi** [esm-bits/novice-timer#29]

**Comment by hironoriohashi** [comment]
登録済みのアジェンダの内容を更新する機能を以下のように考えました。
レビューお願いします。

機能
PUTのリクエストを受けてidで指定されたアジェンダの内容を更新する

インタフェース
リクエスト:
パス:PUT api/agendas/{id}
リクエストボディ:
{
    "subjects": [{
        "title": "タイトル",
        "minutes": 1,
        "idobata_user": "user_name"
    }]
}
レスポンス:
httpステータス:200 OK || 404 NOT FOUND

**Comment by sakai-y** [comment]
N番目の内容だけ修正したい、はナシ？

**Comment by hironoriohashi** [comment]
N番目のsubject内容だけ変えたいということもあります。(LTの時間変更等)
そこまで想定できていませんでした。
以下の機能を追加しました。
レビューお願いします。

インタフェース
リクエスト:
パス:PUT api/agendas/{id}/subjects/{number}/
リクエストボディ:
```json
{
    "title": "タイトル",
    "minutes": 1,
    "idobata_user": "user_name"
}
```
レスポンス:
httpステータス:200 OK || 404 NOT FOUND

**Comment by sakai-y** [comment]
1で。

**Comment by shunji-yamaguchi** [comment]
かしこまりました、ありがとうございます。
