### ISSUE TITLE
入力されたアジェンダを表示する機能を作成する

### ISSUE THREAD

**Issue by hironoriohashi** [esm-bits/novice-timer#3]

**Comment by hironoriohashi** [comment]
GETのリクエストを受け、対応するアジェンダの内容を返す

以上のように考えました。
レビューお願いします

**Comment by sakai-y** [comment]
まあ・・・揺れようがなさそうなw
インターフェース考えましょう。
＃「アジェンダの内容」については「アジェンダ登録」で受け付ける形式と同じになるかもね

**Comment by shunji-yamaguchi** [comment]
#27 で対応
