### ISSUE TITLE
AgendaRestControllerのテストコードを作成する

### ISSUE THREAD

**Issue by hironoriohashi** [esm-bits/novice-timer#33]

**Comment by shunji-yamaguchi** [comment]
以下のように考えました。よろしくお願い致します。

**テスト項目**
- `api/agendas`にGETリクエストすると、`200OK`とアジェンダのリストが返される
- `api/agendas/{id}`にGETリクエストし、idが対応するアジェンダがある場合、`200OK`と対応するidのアジェンダが返される
- `api/agendas/{id}`にGETリクエストし、idが対応するアジェンダがない場合、`404NotFound`が返される
- ’api/agendas’にPOSTリクエストし、ボディにアジェンダを持たせた場合、アジェンダが登録され、`201Created`と登録されたアジェンダが返される
- ’api/agendas/{id}/subjects/{number}’にPUTリクエストし、idが対応するアジェンダがない場合、`400BadRequest`が返される
- ’api/agendas/{id}/subjects/{number}’にPUTリクエストし、numberが不正の場合、'404NotFound'が返される
- ’api/agendas/{id}/subjects/{number}’にPUTリクエストし、ボディの`state`が'start'の場合、`200OK`が返される
- ’api/agendas/{id}/subjects/{number}’にPUTリクエストし、ボディの`state`が'stop'の場合、`200OK`が返される
- ’api/agendas/{id}/subjects/{number}’にPUTリクエストし、ボディの`state`が不正な場合、`400BadRequest`が返される

**Comment by sakai-y** [comment]
🆗
