### ISSUE TITLE
テストコードを記述したファイルの移動

### ISSUE THREAD

**Issue by hironoriohashi** [esm-bits/novice-timer#41]
ファイルを
`src/main/...` から
`src/test/...`の適切な場所へ移動する

**Comment by shunji-yamaguchi** [comment]
テストクラスを`src/main`に置いたまま`gradle build`すると、`src/main`にあるテストクラスでTest.classなどが見つけられずエラーとなる。

GradleではJavaプラグインに関する規約として
- `src/main/java`ディレクトリ配下にプロダクションコードのソースファイルを配置すること
- `src/main/resource`ディレクトリ配下にプロダクションコードのリソースを配置すること
- `src/test/java`ディレクトリ配下にテストコードのソースファイルを配置すること
- `src/test/resources`ディレクトリ配下にテストコードのリソースを配置すること

と決められている。
GradleのJavaプラグインでは、指定のない場合は以上のようなディレクトリー構成を想定する。
これを守ることで最低限の記述でビルドスクリプトを実行できるようになっている。
そのため`src/main`ではテストに関するJavaプラグインは読み込まれておらずエラーとなる。

**Comment by hironoriohashi** [comment]
テストコードのフィールドの修飾子を統一する。
