### ISSUE TITLE
README.mdに開発環境を記述する

### ISSUE THREAD

**Issue by hironoriohashi** [esm-bits/novice-timer#47]

**Comment by hironoriohashi** [comment]
README.mdに以下の項目を追加しようと思います。レビューお願いします。

- IDE
Eclipse Neon.3 (4.6.3)

- フレームワーク
SpringBoot (1.5.4)

- 追加ライブラリ
spring-boot-starter-web (1.5.4)
lombok (1.16.16)

**Comment by fossamagna** [comment]
> フレームワーク
> SpringBoot (1.5.4)
> 
> 追加ライブラリ
> spring-boot-starter-web (1.5.4)
> lombok (1.16.16)

Spring Bootくらいはあってもいいかもしれないけど、ライブラリなどはbuild.gradleでわかるので書かなくてもいいかなと思います。

**Comment by hironoriohashi** [comment]
分かりました。

**Comment by shunji-yamaguchi** [comment]
README.mdに以下の項目を追加しようと思います。レビューをよろしくお願いいたします。

----

**開発環境**
- IDE
Eclipse Neon.3 (4.6.3)

- フレームワーク
SpringBoot (1.5.4)

**導入方法（eclipseの場合）**
- gitでmasterブランチをclone
- EclipseのインポートでGradleプロジェクトを選択してインポート
- プロジェクト右クリック→Gradle→Gradleプロジェクトのリフレッシュ

**実行方法**
- `src/main/resources/config/application.yml`ファイルに通知を送るidobataのフックurlを記述する、ただしGitHubで表示させないためurlの記述のないダミーファイルとしている
- `application-production.yml`を作成し実際のフックurlを記述し、Gitの管理から外している
- 通常どおりに実行すると設定ファイルとして`application.yml`が読み込まれる。
- `application-production.yml`を読み込むは実行時に環境変数`SPRING_PROFILES_ACTIVE = production`を指定する。（eclipseの場合、実行→実行の構成→環境、に記述）
- 通知を送りたくない場合、TimerService.NoticeTimerTaskのsendMessageメソッドの処理をSystem.out.println等に変更するとよい

**操作方法**
- アジェンダの全取得
パス: GET api/agendas

- 特定のアジェンダの取得
パス: GET api/agendas/{id}

- アジェンダの登録
　パス: POST api/agendas
　リクエストボディ: 
````json
{
    "subjects": [
        {
            "title": "タイトル",
            "minutes": 1,
            "idobata_user": "ユーザー"
        }
    ]
}
````

- タイマーの開始
　注意: タイマーの実行は同時に1つのみ、実行中のタイマーがある場合は開始されない
　パス: PUT api/agendas/{id}/subjects/{number}
　リクエストボディ: 
````json
{
  "state": "start"
}
````

- タイマーの終了
　パス: PUT api/agendas/{id}/subjects/{number}
　リクエストボディ: 
````json
{
  "state": "stop"
}
````

- アジェンダの更新
　作成中
　タイマーの開始/終了のパスを`PUT api/agendas/{id}/subjects/{number}/timers`に変更予定

- サブジェクトの更新
　作成中

- アジェンダの削除
　作成中

- 備考：現在Viewを作成していないためRESTクライアントツールを使用して操作する
　- curlコマンド 
　- [Restlet Client - REST API Testing](https://chrome.google.com/webstore/detail/restlet-client-rest-api-t/aejoelaoggembcahagimdiliamlcdmfm)

**デプロイ先**
- Heroku

**参考書**
- 槙俊明（2016）『はじめてのSpringBoot［改訂版］』工学社.

**Comment by shunji-yamaguchi** [comment]
以下の内容をREADME.mdに記述しようと思います、よろしくお願いいたします。

----

**README.mdに記述する内容**
- 開発環境

- 使用しているフレームワーク

- プロジェクトの導入方法

- タイマーアプリの実行方法

- タイマーアプリの操作方法

- デプロイ先

- 参考書
